language: node_js
node_js:
- 8.4.0
after_success:
- npm run coverage
- codeclimate-test-reporter < ./reports/coverage/lcov.info
deploy:
  provider: heroku
  api_key:
    secure: VRpMGchfjWbdqrd0S4+xjPT1BaQPi4l7YQchnO7gYPDC5FTnwK2NqwfXfsPE3n1mDfwnxhT0l0joLQ55RDidzhNlRD5h9efhf/1WiwbxKIK7esjrpU3FKYHWo/CEigLXj+t88C1Hqq8DxZsqRFIIgEkTUMlLAn5GN1GyXr1xmw8trndDDqGsNPi6sG2muH6YkwJ092HVGY06DawEABgKD5ca17xuyq0oygTLkdIocVB89/dH7nOLiHLacMKcyhjsHH4qSGmkspX5pYwCqg8voqi5Ep0p1dAySyRgakx8XkEUQ36uK0S/XyaeJ5d9+IifrrmaR3dUyw1A+lmg0rx5uyrm1nEr5cwuVkQtdOoT4NJocD+19ZucY057GACVzBjzo4ZbzcB/RooNoRtaP3iiQ9vFhguh5TieVcTEVgEv7V3aOgpS9Ivef3KR3QxqYYpNHmO2iqQvpf04GT2pareZCC2Du7AX+XrwAnq9B+OEc8cR+4xYI3o/ztp1mjLRdL+UqlYHWc5tjI5o5IwSdoC0KqTK0eXcXrC72fbt6imURhO5/JSazF/2tsl6AJRk7tXOKeMqvmWAFI8I12/0zMBZVpWN2cCUD0OYgPCd2W8QikykXJpq8Wsbz834Uhv3ypt/MfJBIM5W/cWHmbEW/Ez6Bp2+ffez+kOxK9R+GB05HXQ=
  app: taxnuke-url-shortener
  on:
    repo: taxnuke/url-shortener
